name: squint
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    # Core ML
    - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu124
    - torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cu124
    - tensordict==0.7.2
    - torchrl==0.7.2

    # Environment
    - mani_skill_nightly
    - gymnasium

    # Utilities
    - numpy
    - tyro
    - tqdm
    - wandb
    - opencv-python==4.12.0.88
  
    # Deploy 
    - lerobot[feetech]==0.4.3
